name: TypeScript Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalando dependências
        run: yarn

      - name: Run TypeScript Build
        run: yarn build
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Instalando dependências
        run: yarn

      - name: Run Testes
        run: yarn test
