name: Deploy to production

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'

    steps:
      - name: Deploy to production
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ secrets.PRODUCTION_KEY }}"
